# Generated by Django 5.2.2 on 2025-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumerologyId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(unique=True)),
                ('mind_num', models.PositiveSmallIntegerField()),
                ('heart_num', models.PositiveSmallIntegerField()),
                ('practical_num', models.PositiveSmallIntegerField()),
                ('create_id', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
