# Generated by Django 5.2.2 on 2025-09-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_admine',
            field=models.BooleanField(default=False),
        ),
    ]
