# Generated by Django 5.2.2 on 2025-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_signup_is_admine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
