# Generated by Django 5.2.2 on 2026-01-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_login_datetime_alter_login_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name': 'User Login', 'verbose_name_plural': 'User Logins'},
        ),
        migrations.AddField(
            model_name='login',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
